CREATE TABLE TB_CLIENTES (
    CPF VARCHAR2(11) NOT NULL,
    NOME VARCHAR2 (100),
    ENDERECO1 VARCHAR2(150),
    ENDERECO2 VARCHAR2(150),
    BAIRRO VARCHAR2(50),
    CIDADE VARCHAR2(50),
    ESTADO VARCHAR2(2),
    CEP VARCHAR2(8),
    IDADE INT,
    SEXO VARCHAR2(1),
    LIMITE_CREDITO FLOAT,
    VOLUME_COMPRA FLOAT,
    PRIMEIRA_COMPRA NUMBER(1),
    PRIMARY KEY (CPF)
);

CREATE TABLE TB_VENDEDORES (
    MATRICULA VARCHAR2(5) NOT NULL,
    NOME VARCHAR2(100),
    PERCENTUAL_COMISSAO FLOAT,
    PRIMARY KEY (MATRICULA)
);

CREATE TABLE TB_PRODUTOS (
    COD_PRODUTO VARCHAR2(20) NOT NULL,
    NOME VARCHAR2(150),
    EMBALAGEM VARCHAR2(50),
    TAMANHO VARCHAR2(50),
    SABOR VARCHAR2(50),
    PRECO_LISTA FLOAT,
    PRIMARY KEY (COD_PRODUTO)
);